// <auto-generated />
namespace Aon.MyAon.Persistence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initialcreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201309040333423_initialcreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
